### ISSUE TITLE
Write a roadmap for the next month

### ISSUE THREAD

**Issue by AFFogarty** [DDMAL/Interactive-Classifier#8]
We need to establish goals for the next month of development.

**Comment by AFFogarty** [comment]
I've started writing the roadmap here: https://github.com/DDMAL/Interactive-Classifier/wiki/May-2016-Roadmap.

**Comment by fujinaga** [comment]
This looks good.
Please test this on some music, probably start with St. Gall then Liber and Salzinnes. (Don’t worry too much about how to properly label the glyphs.)
Then do some usability tests, start with Gabriel, fix the issues he raises then repeat the same with Ryan, then Emily.
Don’t worry too much about optimizing at this point.
Also make sure that the documentation is good so that someone can easily take over when you leave.
